<a href="https://colab.research.google.com/github/Denniskag/Data_Visualisation/blob/main/Tanzania_tourism.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [1]:
import pandas as pd

Tanzania Tourism Dataset

In [26]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/Tanzania tourism/Train.csv')

In [ ]:
df.describe()

Global Tourism Datasets

In [3]:
df1 = pd.read_csv('/content/drive/MyDrive/Datasets/Tanzania tourism/ones to use/4- international-tourist-trips.csv')

In [4]:
df2= pd.read_csv('/content/drive/MyDrive/Datasets/Tanzania tourism/ones to use/10- average-length-of-stay.csv')

In [5]:
df3= pd.read_csv('/content/drive/MyDrive/Datasets/Tanzania tourism/ones to use/20- average-expenditures-of-tourists-abroad.csv')

In [6]:
df.head()

,ID,country,age_group,travel_with,total_female,total_male,purpose,main_activity,info_source,tour_arrangement,...,package_transport_tz,package_sightseeing,package_guided_tour,package_insurance,night_mainland,night_zanzibar,payment_mode,first_trip_tz,most_impressing,total_cost
0,tour_0,SWIZERLAND,45-64,Friends/Relatives,1.0,1.0,Leisure and Holidays,Wildlife tourism,"Friends, relatives",Independent,...,No,No,No,No,13.0,0.0,Cash,No,Friendly People,674602.5
1,tour_10,UNITED KINGDOM,25-44,NaN,1.0,0.0,Leisure and Holidays,Cultural tourism,others,Independent,...,No,No,No,No,14.0,7.0,Cash,Yes,"Wonderful Country, Landscape, Nature",3214906.5
2,tour_1000,UNITED KINGDOM,25-44,Alone,0.0,1.0,Visiting Friends and Relatives,Cultural tourism,"Friends, relatives",Independent,...,No,No,No,No,1.0,31.0,Cash,No,Excellent Experience,3315000.0
3,tour_1002,UNITED KINGDOM,25-44,Spouse,1.0,1.0,Leisure and Holidays,Wildlife tourism,"Travel, agent, tour operator",Package Tour,...,Yes,Yes,Yes,No,11.0,0.0,Cash,Yes,Friendly People,7790250.0
4,tour_1004,CHINA,1-24,NaN,1.0,0.0,Leisure and Holidays,Wildlife tourism,"Travel, agent, tour operator",Independent,...,No,No,No,No,7.0,4.0,Cash,Yes,No comments,1657500.0

In [7]:
df.shape

(4809, 23)

In [ ]:
len(df.columns)

23

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     4809 non-null   object
 1   country                4809 non-null   object
 2   age_group              4809 non-null   object
 3   travel_with            3695 non-null   object
 4   total_female           4806 non-null   float64
 5   total_male             4804 non-null   float64
 6   purpose                4809 non-null   object
 7   main_activity          4809 non-null   object
 8   info_source            4809 non-null   object
 9   tour_arrangement       4809 non-null   object
 10  package_transport_int  4809 non-null   object
 11  package_accomodation   4809 non-null   object
 12  package_food           4809 non-null   object
 13  package_transport_tz   4809 non-null   object
 14  package_sightseeing    4809 non-null   object
 15  package_guided_tour    4809 non-null   object
 16  package_insurance      4809 non-null   object
 17  night_mainland         4809 non-null   float64
 18  night_zanzibar         4809 non-null   float64
 19  payment_mode           4809 non-null   object
 20  first_trip_tz          4809 non-null   object
 21  most_impressing        4496 non-null   object
 22  total_cost             4809 non-null   float64
dtypes: float64(5), object(18)
memory usage: 864.2+ KB

In [9]:
df.isnull().sum()

ID                          0
country                     0
age_group                   0
travel_with              1114
total_female                3
total_male                  5
purpose                     0
main_activity               0
info_source                 0
tour_arrangement            0
package_transport_int       0
package_accomodation        0
package_food                0
package_transport_tz        0
package_sightseeing         0
package_guided_tour         0
package_insurance           0
night_mainland              0
night_zanzibar              0
payment_mode                0
first_trip_tz               0
most_impressing           313
total_cost                  0
dtype: int64

In [10]:
mean_female = df['total_female'].mean()
mean_male = df['total_male'].mean()
df['total_female'].fillna(mean_female, inplace=True)
df['total_male'].fillna(mean_male, inplace=True)

# Replace 'most_impressing' with the mode
mode_most_impressing = df['most_impressing'].mode()[0]
df['most_impressing'].fillna(mode_most_impressing, inplace=True)

In [11]:
df['travel_with'].fillna('Uknown', inplace=True)

In [12]:
df.isnull().sum()

ID                       0
country                  0
age_group                0
travel_with              0
total_female             0
total_male               0
purpose                  0
main_activity            0
info_source              0
tour_arrangement         0
package_transport_int    0
package_accomodation     0
package_food             0
package_transport_tz     0
package_sightseeing      0
package_guided_tour      0
package_insurance        0
night_mainland           0
night_zanzibar           0
payment_mode             0
first_trip_tz            0
most_impressing          0
total_cost               0
dtype: int64

In [ ]:
# This will save the DataFrame to a CSV file without including the index
#df.to_csv('Tanzania.csv', index=False)

In [13]:
df.columns

Index(['ID', 'country', 'age_group', 'travel_with', 'total_female',
       'total_male', 'purpose', 'main_activity', 'info_source',
       'tour_arrangement', 'package_transport_int', 'package_accomodation',
       'package_food', 'package_transport_tz', 'package_sightseeing',
       'package_guided_tour', 'package_insurance', 'night_mainland',
       'night_zanzibar', 'payment_mode', 'first_trip_tz', 'most_impressing',
       'total_cost'],
      dtype='object')

In [14]:
df.most_impressing.value_counts()

most_impressing
Friendly People                         1854
 Wildlife                               1038
No comments                              743
Wonderful Country, Landscape, Nature     507
Good service                             365
Excellent Experience                     271
Satisfies and Hope Come Back              31
Name: count, dtype: int64

In [15]:
df.travel_with.value_counts()

travel_with
Alone                  1265
Uknown                 1114
Spouse                 1005
Friends/Relatives       895
Spouse and Children     368
Children                162
Name: count, dtype: int64

In [16]:
df.country.value_counts()

country
UNITED STATES OF AMERICA    695
UNITED KINGDOM              533
ITALY                       393
FRANCE                      280
ZIMBABWE                    274
                           ...
NIGER                         1
MYANMAR                       1
DOMINICA                      1
TUNISIA                       1
ESTONIA                       1
Name: count, Length: 105, dtype: int64

In [17]:
df.describe()

       total_female   total_male  night_mainland  night_zanzibar    total_cost
count   4809.000000  4809.000000     4809.000000     4809.000000  4.809000e+03
mean       0.926758     1.009575        8.488043        2.304429  8.114389e+06
std        1.287840     1.138273       10.427624        4.227080  1.222490e+07
min        0.000000     0.000000        0.000000        0.000000  4.900000e+04
25%        0.000000     1.000000        3.000000        0.000000  8.121750e+05
50%        1.000000     1.000000        6.000000        0.000000  3.397875e+06
75%        1.000000     1.000000       11.000000        4.000000  9.945000e+06
max       49.000000    44.000000      145.000000       61.000000  9.953288e+07

In [25]:
df.describe(include="O").T

                      count unique                           top  freq
ID                     4809   4809                        tour_0     1
country                4809    105      UNITED STATES OF AMERICA   695
age_group              4809      4                         25-44  2487
travel_with            4809      6                         Alone  1265
purpose                4809      7          Leisure and Holidays  2840
main_activity          4809      9              Wildlife tourism  2259
info_source            4809      8  Travel, agent, tour operator  1913
tour_arrangement       4809      2                   Independent  2570
package_transport_int  4809      2                            No  3357
package_accomodation   4809      2                            No  2602
package_food           4809      2                            No  2748
package_transport_tz   4809      2                            No  2919
package_sightseeing    4809      2                            No  3319
package_guided_tour    4809      2                            No  3259
package_insurance      4809      2                            No  4079
payment_mode           4809      4                          Cash  4172
first_trip_tz          4809      2                           Yes  3243
most_impressing        4809      7               Friendly People  1854

In [18]:
df1.isnull().sum()

Entity                         0
Code                           0
Year                           0
Inbound arrivals (tourists)    0
dtype: int64

In [19]:
df2.isnull().sum()

Entity                    0
Code                      0
Year                      0
Average length of stay    0
dtype: int64

In [20]:
df3.isnull().sum()

Entity                                                           0
Code                                                             0
Year                                                             0
Outbound Tourism Expenditure (adjusted for US 2021 inflation)    0
dtype: int64

In [21]:
df3.Year.value_counts()

Year
2008    51
2009    51
2020    51
2019    51
2018    51
2017    51
2016    51
2015    51
2014    51
2013    51
2012    51
2011    51
2010    51
2021    51
2007    51
2006    51
2005    51
2004    50
1996    49
2003    49
2002    49
2001    49
2000    49
1999    49
1998    49
1997    49
1995    49
Name: count, dtype: int64

In [22]:
df1.describe()

              Year  Inbound arrivals (tourists)
count  4940.000000                 4.940000e+03
mean   2007.850202                 4.325684e+06
std       7.671389                 1.056018e+07
min    1995.000000                 1.000000e+00
25%    2001.000000                 1.560000e+05
50%    2008.000000                 6.060000e+05
75%    2014.000000                 2.916750e+06
max    2021.000000                 9.091400e+07

In [23]:
df2.describe()

              Year  Average length of stay
count  2894.000000             2894.000000
mean   2008.046303                4.459173
std       7.508304                3.272503
min    1995.000000                0.600000
25%    2002.000000                2.200000
50%    2008.000000                3.085000
75%    2014.000000                6.270000
max    2021.000000               23.000000

In [24]:
df3.describe()

,Year,Outbound Tourism Expenditure (adjusted for US 2021 inflation)
count,1358.000000,1.358000e+03
mean,2008.122239,1.439090e+10
std,7.769890,2.260691e+10
min,1995.000000,4.267707e+07
25%,2001.000000,1.825300e+09
50%,2008.000000,5.408485e+09
75%,2015.000000,1.685072e+10
max,2021.000000,1.401954e+11